services:
  usuario:
    build: ./usuario
    image: ${DOCKER_HUB_USER:-nyko115}/sanos-salvos-usuario:${IMAGE_TAG:-latest}

  mascotas:
    build: ./mascotas
    image: ${DOCKER_HUB_USER:-nyko115}/sanos-salvos-mascotas:${IMAGE_TAG:-latest}

  reportes:
    build: ./reportes
    image: ${DOCKER_HUB_USER:-nyko115}/sanos-salvos-reportes:${IMAGE_TAG:-latest}

  apigateway:
    build: ./apigateway
    image: ${DOCKER_HUB_USER:-nyko115}/sanos-salvos-apigateway:${IMAGE_TAG:-latest}
