services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-user_adm}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Nykolas2111}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  usuario:
    image: ${DOCKER_HUB_USER:-nyko115}/sanos-salvos-usuario:${IMAGE_TAG:-latest}
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: usuario_db
      DB_USER: ${DB_USER:-user_adm}
      DB_PASSWORD: ${DB_PASSWORD:-Nykolas2111}
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  mascotas:
    image: ${DOCKER_HUB_USER:-nyko115}/sanos-salvos-mascotas:${IMAGE_TAG:-latest}
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mascotas_db
      DB_USER: ${DB_USER:-user_adm}
      DB_PASSWORD: ${DB_PASSWORD:-Nykolas2111}
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  reportes:
    image: ${DOCKER_HUB_USER:-nyko115}/sanos-salvos-reportes:${IMAGE_TAG:-latest}
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: reportes_db
      DB_USER: ${DB_USER:-user_adm}
      DB_PASSWORD: ${DB_PASSWORD:-Nykolas2111}
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  apigateway:
    image: ${DOCKER_HUB_USER:-nyko115}/sanos-salvos-apigateway:${IMAGE_TAG:-latest}
    ports:
      - "8080:8080"
    depends_on:
      - usuario
      - mascotas
      - reportes

  db-sonarqube:
    image: postgres:16-alpine
    container_name: db-sonarqube
    environment:
      POSTGRES_USER: sonar           
      POSTGRES_PASSWORD: sonar_1234  
      POSTGRES_DB: sonar
    volumes:
      - sonar-db-data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - db-sonarqube
    environment:
      SONAR_JDBC_USERNAME: sonar          
      SONAR_JDBC_PASSWORD: sonar_1234     
      SONAR_JDBC_URL: jdbc:postgresql://db-sonarqube:5432/sonar
    ports:
      - "9000:9000"
    volumes:
      - sonar-data:/opt/sonarqube/data
      - sonar-extensions:/opt/sonarqube/extensions
      - sonar-logs:/opt/sonarqube/logs

volumes:
  postgres-data:
  sonar-db-data:
  sonar-data:
  sonar-extensions:
  sonar-logs: