DROP TABLE IF EXISTS usuario;

CREATE TABLE usuario (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut         VARCHAR(255),
    nombre      VARCHAR(255),
    apellido    VARCHAR(255),
    email       VARCHAR(255),
    telefono    INTEGER,
    password    VARCHAR(255),
    activo      BOOLEAN,
    rol         VARCHAR(20)
);