DROP TABLE IF EXISTS mascota_senas;
DROP TABLE IF EXISTS notificaciones_match;
DROP TABLE IF EXISTS mascotas;

CREATE TABLE mascotas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(255),
    especie       VARCHAR(50),
    raza          VARCHAR(255),
    color         VARCHAR(255),
    pelaje        VARCHAR(255),
    tamano        VARCHAR(255),
    rango_edad    VARCHAR(255),
    estado        VARCHAR(50),
    descripcion   VARCHAR(1000),
    contacto      VARCHAR(255),
    edad          INTEGER,
    usuario_id    BIGINT,
    foto_url      TEXT,
    lat           DOUBLE,
    lng           DOUBLE,
    fecha_reporte TIMESTAMP
);

CREATE TABLE mascota_senas (
    mascota_id BIGINT NOT NULL REFERENCES mascotas(id),
    sena       VARCHAR(50)
);

CREATE TABLE notificaciones_match (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id           BIGINT,
    mascota_id_perdida   BIGINT,
    mascota_id_candidata BIGINT,
    score                DOUBLE,
    porcentaje           INTEGER,
    mensaje              VARCHAR(500),
    fecha_notificacion   TIMESTAMP,
    leida                BOOLEAN DEFAULT FALSE
);
