DROP TABLE IF EXISTS mascotas;

CREATE TABLE mascotas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    especie VARCHAR(50),
    raza VARCHAR(255),
    color VARCHAR(255),
    pelaje VARCHAR(255),
    tamano VARCHAR(255),
    rango_edad VARCHAR(255),
    estado VARCHAR(50),
    descripcion VARCHAR(1000),
    edad INTEGER,
    usuario_id BIGINT,
    foto_url VARCHAR(500),
    lat DOUBLE,
    lng DOUBLE,
    fecha_reporte TIMESTAMP
);