DROP TABLE IF EXISTS mascotas;

CREATE TABLE mascotas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(255),
    raza        VARCHAR(255),
    edad        INTEGER,
    descripcion VARCHAR(255),
    usuario_id  BIGINT,
    especie     VARCHAR(20),
    estado      VARCHAR(20)
);