DROP TABLE IF EXISTS reportes;

CREATE TABLE reportes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_mascota  VARCHAR(255),
    nombre_usuario  VARCHAR(255),
    usuario_id      BIGINT,
    mascota_id      BIGINT,
    descripcion     VARCHAR(255),
    fecha_reporte   DATE,
    telefono        INTEGER,
    latitude        DOUBLE,
    longitude       DOUBLE,
    img             VARCHAR(255),
    estado          VARCHAR(20)
    -- Sin check constraint para el enum, H2 acepta cualquier valor VARCHAR
);