spring.application.name=apigateway

server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=servicio-usuario
spring.cloud.gateway.server.webmvc.routes[0].uri=${USUARIO_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/usuario/**

spring.cloud.gateway.server.webmvc.routes[1].id=servicio-mascota
spring.cloud.gateway.server.webmvc.routes[1].uri=${MASCOTAS_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/mascotas/**

spring.cloud.gateway.server.webmvc.routes[2].id=servicio-reportes
spring.cloud.gateway.server.webmvc.routes[2].uri=${REPORTES_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/reportes/**

security.jwt.secret=jwt_secret_sanos_salvos_2026_clave_muy_segura_12345>

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
