spring.application.name=apigateway

server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=servicio-usuario
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/usuario/**

security.jwt.secret=NicolasAlbertoRamosRivera2128...