spring.application.name=usuario

spring.datasource.url=jdbc:postgresql://localhost:5432/usuario_db
spring.datasource.username=user_adm
spring.datasource.password=Nykolas2111
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

# Debe coincidir con la clave configurada en el API Gateway
security.jwt.secret=jwt_secret_sanos_salvos_2026_clave_muy_segura_12345
security.jwt.expiration-ms=86400000

mascotas.service.url=http://localhost:8080,http://localhost:8082

