spring.application.name=usuario

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:usuario_db}
spring.datasource.username=${DB_USER:user_adm}
spring.datasource.password=${DB_PASSWORD:Nykolas2111}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

# Debe coincidir con la clave configurada en el API Gateway
security.jwt.secret=jwt_secret_sanos_salvos_2026_clave_muy_segura_12345
security.jwt.expiration-ms=86400000

mascotas.service.url=http://mascotas:8082

