spring.application.name=usuario

spring.datasource.url=jdbc:postgresql://localhost:5432/usuario_db
spring.datasource.username=user_adm
spring.datasource.password=Nykolas2111
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

# Debe coincidir con la clave configurada en el API Gateway
security.jwt.secret=CAMBIA_ESTA_CLAVE_POR_UNA_DE_32_O_MAS_CARACTERES
security.jwt.expiration-ms=86400000

