--
-- PostgreSQL database dump
--

\restrict sgqcbPPejT5PhEvoTO4GFfzAaQ0su0aJrAEYa26iPcRdiVgKrVmEffZcSBDjAML

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: mascotas; Type: TABLE; Schema: public; Owner: user_adm
--

CREATE TABLE public.mascotas (
    id bigint NOT NULL,
    descripcion character varying(255),
    edad integer,
    especie character varying(255),
    estado character varying(255),
    nombre character varying(255),
    raza character varying(255),
    usuario_id bigint,
    CONSTRAINT mascotas_especie_check CHECK (((especie)::text = ANY ((ARRAY['PERRO'::character varying, 'GATO'::character varying, 'HURON'::character varying, 'ROEDOR'::character varying, 'OTRO'::character varying])::text[]))),
    CONSTRAINT mascotas_estado_check CHECK (((estado)::text = ANY ((ARRAY['ENCONTRADO'::character varying, 'PERDIDO'::character varying])::text[])))
);


ALTER TABLE public.mascotas OWNER TO user_adm;

--
-- Name: mascotas_id_seq; Type: SEQUENCE; Schema: public; Owner: user_adm
--

ALTER TABLE public.mascotas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mascotas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: mascotas; Type: TABLE DATA; Schema: public; Owner: user_adm
--

COPY public.mascotas (id, descripcion, edad, especie, estado, nombre, raza, usuario_id) FROM stdin;
1	Pug de color negro, mide 50cm, esta un poco pasado de peso y tiene una mancha blanca en el pecho	8	PERRO	ENCONTRADO	Black	Pug	2
\.


--
-- Name: mascotas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user_adm
--

SELECT pg_catalog.setval('public.mascotas_id_seq', 1, true);


--
-- Name: mascotas mascotas_pkey; Type: CONSTRAINT; Schema: public; Owner: user_adm
--

ALTER TABLE ONLY public.mascotas
    ADD CONSTRAINT mascotas_pkey PRIMARY KEY (id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO user_adm;


--
-- PostgreSQL database dump complete
--

\unrestrict sgqcbPPejT5PhEvoTO4GFfzAaQ0su0aJrAEYa26iPcRdiVgKrVmEffZcSBDjAML

