--
-- PostgreSQL database dump
--

\restrict YuTeJNLan1ttbrjeh7ye2GG7FWktuv75nJpgPO65WQlp53xIZl2NEQvZhpQcgyo

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: reportes; Type: TABLE; Schema: public; Owner: user_adm
--

CREATE TABLE public.reportes (
    id bigint NOT NULL,
    descripcion character varying(255),
    estado character varying(255),
    fecha_reporte date,
    img character varying(255),
    mascota_id bigint,
    nombre_mascota character varying(255),
    nombre_usuario character varying(255),
    latitude double precision,
    longitude double precision,
    usuario_id bigint,
    telefono integer,
    coordenadas character varying(255),
    CONSTRAINT reportes_estado_check CHECK (((estado)::text = ANY ((ARRAY['ENCONTRADO'::character varying, 'PERDIDO'::character varying])::text[])))
);


ALTER TABLE public.reportes OWNER TO user_adm;

--
-- Name: reportes_id_seq; Type: SEQUENCE; Schema: public; Owner: user_adm
--

ALTER TABLE public.reportes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reportes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: reportes; Type: TABLE DATA; Schema: public; Owner: user_adm
--

COPY public.reportes (id, descripcion, estado, fecha_reporte, img, mascota_id, nombre_mascota, nombre_usuario, latitude, longitude, usuario_id, telefono, coordenadas) FROM stdin;
3	Perro pug negro tiene una mancha blanca en el pecho le gusta jugar y ladrarle a las motos si lo ven llamar a este numero +56 9 2600 3773	PERDIDO	2026-05-29	https://pub-daffd7e8a85c4df4a96cdc1e8f6b61e8.r2.dev/imagenes/black.jpg	1	\N	\N	-33.512351019102496	-70.75375556945802	2	\N	\N
4	Miguel es un gatito estrabagante por su baja estatura le gusta comer y escalar si lo ven porfavor llamar a este numero +56 9 8756 4535	PERDIDO	2026-05-30	https://pub-daffd7e8a85c4df4a96cdc1e8f6b61e8.r2.dev/imagenes/miguel.jpg	\N	Miguel	Paconi	-33.50698364409982	-70.75246810913087	\N	987564535	\N
2	Es una gatita que le encanta esconderse en cajitas y le encanta dormir. si la ven porfavor llamar a este numero +56 9 5345 6654	PERDIDO	2026-05-29	https://pub-daffd7e8a85c4df4a96cdc1e8f6b61e8.r2.dev/imagenes/20250410_125308.jpg	\N	Cristina 	Kiara	-33.51080167365354	-70.74843406677248	\N	953456654	\N
5	Este perrito se perdio a las 3:00 pm mato a 3 Pastores alemanes y se fue corriendo. tener cuidado si lo ven avisar al telefono registrado	PERDIDO	2026-05-30	https://pub-daffd7e8a85c4df4a96cdc1e8f6b61e8.r2.dev/imagenes/Destructor.jpg	\N	Destructor De Mundos 	Mauricio	-33.50890878263809	-70.76474189758302	\N	966754596	\N
6	este gatito te kiere mucho 	ENCONTRADO	2026-06-01	https://pub-daffd7e8a85c4df4a96cdc1e8f6b61e8.r2.dev/imagenes/tkm.jpg	\N	Pepito	armando barreras	-33.50468690387368	-70.76851844787599	\N	953436576	\N
7	Mascota perdida este domingo 31 de mayo 	PERDIDO	2026-06-01	https://pub-daffd7e8a85c4df4a96cdc1e8f6b61e8.r2.dev/imagenes/leon.jpg	\N	Leon	Vivi	-33.44189624443741	-70.74491500854494	\N	940243486	\N
\.


--
-- Name: reportes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user_adm
--

SELECT pg_catalog.setval('public.reportes_id_seq', 7, true);


--
-- Name: reportes reportes_pkey; Type: CONSTRAINT; Schema: public; Owner: user_adm
--

ALTER TABLE ONLY public.reportes
    ADD CONSTRAINT reportes_pkey PRIMARY KEY (id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO user_adm;


--
-- PostgreSQL database dump complete
--

\unrestrict YuTeJNLan1ttbrjeh7ye2GG7FWktuv75nJpgPO65WQlp53xIZl2NEQvZhpQcgyo

