spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.application.name=reportes

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:reportes_db}
spring.datasource.username=${DB_USER:user_adm}
spring.datasource.password=${DB_PASSWORD:Nykolas2111}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8083

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

security.jwt.secret=jwt_secret_sanos_salvos_2026_clave_muy_segura_12345

usuario.service.urls=http://usuario:8081
mascotas.service.url=http://mascotas:8082

cloudflare.account.id=ac5ab01d170571ad0591825a232ec6e0
cloudflare.api.token=cfat_aUv2x1izAzOb3S43lE0XnC0ZsAK5IVTnO7XoZPDF28a57af0
cloudflare.r2.access-key=c47609b341f913c436e8ba66a9fb4165
cloudflare.r2.secret-key=3eb277029b6f46d30a498f78de5bf20d2d48dff8429bb45b179e7f1e3bf08678
cloudflare.r2.bucket=sanosysalvos
cloudflare.r2.endpoint=https://ac5ab01d170571ad0591825a232ec6e0.r2.cloudflarestorage.com